### ISSUE TITLE
num_samples should be a positive interger

### ISSUE THREAD

**Issue by Oscar310118** [simonwu53/NetCalib2-Sensors-Auto-Calibration#1] opened 2022-04-12 12:40 UTC
Hi,
Now I face a problem that sampler can't find the sample,but my dataset is  already orginized like yours,and the path is changed.It doesn't work.Can you help me to solve this problem,sincerely.
 
num_samples should be a positive intergervalue,but got num_samples=0

**Comment by simonwu53** [comment] 2022-04-12 13:22
Hi, could you also provide the sample code you use and the whole error message output from console that describes the error? Thanks!

**Comment by Oscar310118** [comment] 2022-04-12 13:30
![277421567_749628132670200_8759376265523431565_n](https://user-images.githubusercontent.com/66508452/162973405-037d14a8-04b6-4ddd-8b0d-b9e16ba94eed.png)
Here is my error message,and the sample code is your source code and change the dataset path.

**Comment by simonwu53** [comment] 2022-04-12 16:00
I suspect the error comes from the training dataset 'train_ds'. It is because that the dataset files are not organized as the requirement, the training dataset (train_ds) cannot load dataset files correctly, and the 'total_len' in the training dataset is 0, then cause the error in 'DataLoader'.

### How to check whether it works
You can test with the 'train_ds' instance by yourself and check whether the 'train_ds.total_len' is 0. When loading the dataset files, 'set_mode' function and '_init_data' function are used in 'TrainDataset' class. Make sure these two functions work correctly with your files.

At line 88 in 'dataset.py', 
```
self.drives` = [i.name.split('_')[4] for i in getattr(self, f'{mode}_root').joinpath(self.date).glob(f'{self.date}_drive_*_sync')]
```
here all 'drives' of the KITTI dataset should be loaded.

At line 101 & 102 in 'dataset.py',  the 'loader' should be created correctly and ground truth file path should be correct.

### Possible solutions
either create the correct file structure or adapt the functions mentioned above for your files

**Comment by Oscar310118** [comment] 2022-04-13 01:48
![image](https://user-images.githubusercontent.com/66508452/163082502-3ba7dbc3-8985-4a98-b251-57959e0c2634.png)
Hi,
Here is my dataset organization.It seems that it's the same as requirement.And  I have tried to checked the 'train_ds.total_len'  is 0.Can you help me to check the organization,sincerely.

**Comment by simonwu53** [comment] 2022-04-13 11:56
May I ask for the command line input you use for running the code? Thanks

Because I have exactly the same structure.
<img width="888" alt="fs" src="https://user-images.githubusercontent.com/27355570/163176018-74ed325a-c6a1-4ec9-8ec0-e8f24c39dc58.png">

Then, I built the dataset `ds = TrainDataset('/home/shanwu/dataset/KITTI/')`, and `ds.total_len` outputs `14976`.

However, when you use other path like: `~/dataset/KITTI`, which is the same meaning in `bash`, it won't work, `total_len` will be `0`. Only use the full path of KITTI root, in your case is `dataset_preprocessing`.

**Comment by Oscar310118** [comment] 2022-04-13 11:58
![image](https://user-images.githubusercontent.com/66508452/163175002-300e5c98-b724-4c54-a84f-af5bf2576c82.png)
Sure,here is my training script.

**Comment by simonwu53** [comment] 2022-04-13 12:15
> May I ask for the command line input you use for running the code? Thanks
> 
> Because I have exactly the same structure. <img alt="fs" width="888" src="https://user-images.githubusercontent.com/27355570/163176018-74ed325a-c6a1-4ec9-8ec0-e8f24c39dc58.png">
> 
> Then, I built the dataset `ds = TrainDataset('/home/shanwu/dataset/KITTI/')`, and `ds.total_len` outputs `14976`.
> 
> However, when you use other path like: `~/dataset/KITTI`, which is the same meaning in `bash`, it won't work, `total_len` will be `0`. Only use the full path of KITTI root, in your case is `dataset_preprocessing`.

The issue comes from the `KITTI_DIR` you set, so changing it to `/home/oscar310118/NetCalib2_Sensors_Auto_Calibration/dataset_preprocessing/` will work.

**Comment by Oscar310118** [comment] 2022-04-13 12:32
I have tried the method you provided,but it still failed.I tried to change your train.py like below
![image](https://user-images.githubusercontent.com/66508452/163180096-5f2632ae-f176-4d08-9df6-113f01afc8ef.png)
But the reponse like below
![image](https://user-images.githubusercontent.com/66508452/163180295-fac14b49-3252-4779-aa51-4199924641f0.png)
 Am I misunderstanding your meaning?

**Comment by simonwu53** [comment] 2022-04-13 12:44
![163180295-fac14b49-3252-4779-aa51-4199924641f0](https://user-images.githubusercontent.com/27355570/163182532-ad729bc2-238c-4c8a-b218-4b3dc76ad3ac.png)
It seems the path is not changed. it should be `/home/oscar310118/NetCalib2_Sensors_Auto_Calibration/dataset_preprocessing/`

**Comment by Oscar310118** [comment] 2022-04-13 12:47
But my train_ds is changed like yours.The path is correct.However,it can't work.

**Comment by simonwu53** [comment] 2022-04-13 13:02
Try this:
1. No need to change `train.py`, convert it back to original state. Keep other files untouched too.
2. Modify `KITTY_DIR` to `/home/oscar310118/NetCalib2_Sensors_Auto_Calibration/dataset_preprocessing/` in the file `train.sh` and save it.
3. In the console, run `bash train.sh`.

**Comment by Oscar310118** [comment] 2022-04-13 13:10
I've tried, but it still failed.I use the original train.py.

**Comment by simonwu53** [comment] 2022-04-13 15:39
<img width="1332" alt="fresh_run" src="https://user-images.githubusercontent.com/27355570/163216481-dff3e2d3-a238-4f97-ad91-1b9ba850a442.png">

Here's a fresh run from my side (Python 3.8.2, PyTorch 1.5.0, TorchVision 0.6.0). Only `train.sh` was modified based on my machine and `results/` folder was created manually (under project root directory), code runs without any problem.

<br/><br/>

Creation of `results/` folder should be done automatically, which will be fixed by me later.  [**Update:** issue fixed in [bd11c20](https://github.com/simonwu53/NetCalib2-Sensors-Auto-Calibration/commit/bd11c20d5fd807963b7e54b99fe12c3084a86b81)] Previously, we need to manually create this folder before running the code, and it's not related to your `num_samples` issue.

<br/><br/>

Again, make sure you are modifying and running the correct file and the script you run imports the correct modules.

**Comment by Oscar310118** [comment] 2022-04-14 04:48
Sorry about that, I am not sure how this code worked for. I don't have this file. Is this necessary, sincerely.
![image](https://user-images.githubusercontent.com/66508452/163315581-f302d9b7-960f-4174-9cb5-b7062af5e171.png)

**Comment by simonwu53** [comment] 2022-04-14 14:44
This line of code activates your Python virtual environment if needed. It can be any arbitrary path. If you are not using virtual environment or not sure whether you are using, you can make this line a comment line (add a # at the beginning).

I don't think it's related to your issue.

**Comment by Oscar310118** [comment] 2022-04-17 00:53
Sorry for the late reply. I want to reorganize my dataset. Because my calibration text is copied by another side, I wonder where your calibration text (like calib_imu_to_velo.txt) originated from, thanks.

**Comment by Oscar310118** [comment] 2022-04-17 06:27
And after I trace the code, I find that the_init_data in dataset.py, drive_len is constant 0. The code is modified like below
![image](https://user-images.githubusercontent.com/66508452/163703359-3a0c05f6-9d02-4fb7-a048-0e12b9e321e1.png)
Is that the path's problem?

**Comment by simonwu53** [comment] 2022-04-17 11:25
> Sorry for the late reply. I want to reorganize my dataset. Because my calibration text is copied by another side, I wonder where your calibration text (like calib_imu_to_velo.txt) originated from, thanks.

All files comes from the RAW KITTI data (http://www.cvlibs.net/datasets/kitti/raw_data.php), there you will find "**synced+rectified data**" and "**calibration**" files.

**Comment by simonwu53** [comment] 2022-04-17 11:41
> And after I trace the code, I find that the_init_data in dataset.py, drive_len is constant 0. The code is modified like below
> ![image](https://user-images.githubusercontent.com/66508452/163703359-3a0c05f6-9d02-4fb7-a048-0e12b9e321e1.png)
> Is that the path's problem?

As I stated [here](https://github.com/simonwu53/NetCalib2-Sensors-Auto-Calibration/issues/1#issuecomment-1097980656), we should use dataset root directory for the path. In your case, it will be `/home/oscar310118/NetCalib2_Sensors_Auto_Calibration/dataset_preprocessing/`.

These parameters, `KITTI_DIR` in `train.sh`, `args.dataset` in `train.py`, `self.root` in `dataset.py`, all should be the dataset root directory. In your case, `/home/oscar310118/NetCalib2_Sensors_Auto_Calibration/dataset_preprocessing/`.

The code is functioning as expected, if everything is unchanged, we only need to modify `KITTI_DIR`, and all other parameters will be changed accordingly. If these parameters are not set correctly, `total_len` and `drive_len` in `dataset.py` will be `0`.

Except the method above, you could always write your own `dataset.py` file, which can adapt to any dataset you have and whatever path you want. However, your own version of `dataset` should function as the original one.

**Comment by Oscar310118** [comment] 2022-04-18 22:40
If the path is correct, but still failed.I think the preprocessing procedure is a problem.Here is your preprocess.sh, but I can't find the  mass_production.py.I change to preprocess.py.Is this correct?But I found that it has --no_cam_dapth instead of--process_depth_data.How can I change this parser, thanks.
![螢幕擷取畫面 2022-04-19 063154](https://user-images.githubusercontent.com/66508452/163888487-3f7ce69b-9e3d-44e9-aa9d-7b78fe64036d.jpg)
![螢幕擷取畫面 2022-04-19 063218](https://user-images.githubusercontent.com/66508452/163888503-00c74a42-19ad-4a67-8bc5-fe139e73851a.jpg)
![螢幕擷取畫面 2022-04-19 063239](https://user-images.githubusercontent.com/66508452/163888543-466f66bf-ed11-4420-930f-6e28f2eea9ab.jpg)

**Comment by simonwu53** [comment] 2022-04-19 18:56
Sorry. I have updated the preprocessing script. It was a mess. Now the `preprocess.sh` will find `preprocess.py`, and options are changed accordingly.

In order to run the script, you need an algorithm to generate camera depth maps. Hence, the `preprocess.py` needs a bit modification before using, I added more notes there. That's why there's a `no_cam_depth` option, if enabling this option, script works without any modification, but there will be no `image_c` folder. Due to the lack of time, I didn't organize camera depth algorithms that we tested, and there are many existing ones to use as well. I may add a simple one in the script when I have time later.

**Comment by Oscar310118** [comment] 2022-04-19 23:04
OK, thanks. So I have to modify the preprocess.py and preprocess.sh, right. If I didn't modify the preprocess.py and use the preprocess.sh like upon. Is this worked? Thanks.

**Comment by Oscar310118** [comment] 2022-04-19 23:07
And I have another question. Does it cause a problem because I use python3 instead of python? Or it's not the big deal, thanks.

**Comment by simonwu53** [comment] 2022-04-19 23:35
In the latest [commit](https://github.com/simonwu53/NetCalib2-Sensors-Auto-Calibration/commit/6822021beed9bc43f099b61ed8513351724e8b26), the script `preprocess.sh` has been updated. You can use that as a template and also modify `preprocess.py` if you want to generate camera depth images during the preprocessing. I have added comments for modification there. 

In general, most common Python 3 interpreters can run the code (Python 3.5+), I use version 3.8 for example. Whether to run with `python` or `python3` depends on your system setup. For example, after activating virtual environment on my machine, any `python` command will use my virtual environment's interpreter (still Python 3.8). It's typical when using virtual environment, command with `python` will always use the activated python interpreter. If you don't know which interpreter is being used, try command `python -V` or `which python`. It will show you the python version being used and its executable path. If the version or the executable path showed isn't your desire one, you can always use an explicit path to run the code (e.g. `/Users/username/miniconda/envs/xxx/bin/python code.py`, which is equivalent to `python code.py` when activating virtual environment called `xxx` in `miniconda`).

**Comment by Oscar310118** [comment] 2022-04-19 23:49
So, do you think the preprocess procedure cause the problem? Or it still can work if I use the original one.

**Comment by simonwu53** [comment] 2022-04-19 23:58
To be honest, I don't think your dataset has any problem. Just last check, are the file names in `image_c` and `image_l` folders the same? If they are the same, the dataset is okay.

**Comment by Oscar310118** [comment] 2022-04-20 00:05
After I checked my dataset folder, My image_c is empty. So I will try the new preprocess.sh, and checked the problem will be fixed or not.

**Comment by Oscar310118** [comment] 2022-04-20 00:27
As you mentioned before, I will generate the empty image_c file if I used --no_cam_depth. And my image_c and image_l are different, is this the problem's reason? Thanks.

**Comment by simonwu53** [comment] 2022-04-20 03:16
Yes, the cause 0 `num_samples` issue is because of wrong dataset. In order to have the correct one, we have to make sure:
1. organize dataset folders as shown in README. (you have done correct)
2. the path is correct. (use kitti root folder for `KITTI_DIR`, you did correct after changing)
3. all pictures in `image_c` and `image_l` folders are synced. (See README, it shows the file names of the pictures)

You have empty `image_c` folder, so the script will ignore all these datasets, then the `total_len` and `num_samples` will be 0. If you run the `preprocess.sh` with `--no_cam_depth` flag, the files in `image_c` will be missing. You need to find an algorithm to generate camera depth files and modify `preprocess.py`, then run the `preprocess.sh` without `--no_cam_depth` flag.

**Comment by Oscar310118** [comment] 2022-04-20 23:06
OK, I think this is the problem reason. Would you provide your algorithm to generate camera depth files, thanks.

**Comment by Oscar310118** [comment] 2022-04-22 01:59
Is this possible to provide a simple code to generate camera depth files like the Semi-Global Block Matching you mentioned or the method you implemented, thanks.

**Comment by simonwu53** [comment] 2022-04-24 20:04
> Sorry. I have updated the preprocessing script. It was a mess. Now the `preprocess.sh` will find `preprocess.py`, and options are changed accordingly.
> 
> In order to run the script, you need an algorithm to generate camera depth maps. Hence, the `preprocess.py` needs a bit modification before using, I added more notes there. That's why there's a `no_cam_depth` option, if enabling this option, script works without any modification, but there will be no `image_c` folder. Due to the lack of time, I didn't organize camera depth algorithms that we tested, and there are many existing ones to use as well. I may add a simple one in the script when I have time later.

Hello, as I said, I didn't organize camera depth algorithms yet, which means the algorithms are not integrated with the main pipeline and scripts. Thus, the algorithms were deployed on our specific machine, which cannot be directly used on other machine. 

For SGBM algorithm, it's everywhere out there: https://www.google.com/search?q=opencv+SGBM+python
For more sophisticated ones: https://github.com/search?l=Python&q=camera+depth&type=Repositories

**Comment by Oscar310118** [comment] 2022-04-25 00:55
Thanks a lot. Is it possible to add a simple camera depth data generator if you are available?

**Closed as completed** 2022-04-28 15:01 UTC
